package com.programknock;

import org.junit.jupiter.api.Test;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class SimulateLangtonsAntTest {

    @Test
    void testSteps0() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(0);
        assertTrue(result.isEmpty());
    }

    @Test
    void testSteps1() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(1);
        assertEquals(1, result.size());
        assertEquals(0, result.get(0).x);
        assertEquals(0, result.get(0).y);
    }

    @Test
    void testSteps2() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(2);
        assertEquals(2, result.size());
        assertEquals(0, result.get(0).x);
        assertEquals(0, result.get(0).y);
        assertEquals(1, result.get(1).x);
        assertEquals(0, result.get(1).y);
    }

    @Test
    void testSteps3() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(3);
        assertEquals(3, result.size());
        assertEquals(0, result.get(0).x);
        assertEquals(0, result.get(0).y);
        assertEquals(1, result.get(1).x);
        assertEquals(-1, result.get(1).y);
        assertEquals(1, result.get(2).x);
        assertEquals(0, result.get(2).y);
    }

    @Test
    void testSteps4() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(4);
        assertEquals(4, result.size());
        assertEquals(0, result.get(0).x);
        assertEquals(-1, result.get(0).y);
        assertEquals(0, result.get(1).x);
        assertEquals(0, result.get(1).y);
        assertEquals(1, result.get(2).x);
        assertEquals(-1, result.get(2).y);
        assertEquals(1, result.get(3).x);
        assertEquals(0, result.get(3).y);
    }

    @Test
    void testSteps5() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(5);
        assertEquals(3, result.size());
        assertEquals(0, result.get(0).x);
        assertEquals(-1, result.get(0).y);
        assertEquals(1, result.get(1).x);
        assertEquals(-1, result.get(1).y);
        assertEquals(1, result.get(2).x);
        assertEquals(0, result.get(2).y);
    }

    @Test
    void testSteps6() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(6);
        assertEquals(4, result.size());
        assertEquals(-1, result.get(0).x);
        assertEquals(0, result.get(0).y);
        assertEquals(0, result.get(1).x);
        assertEquals(-1, result.get(1).y);
        assertEquals(1, result.get(2).x);
        assertEquals(-1, result.get(2).y);
        assertEquals(1, result.get(3).x);
        assertEquals(0, result.get(3).y);
    }

    @Test
    void testSteps7() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(7);
        assertEquals(5, result.size());
        assertEquals(-1, result.get(0).x);
        assertEquals(0, result.get(0).y);
        assertEquals(-1, result.get(1).x);
        assertEquals(1, result.get(1).y);
        assertEquals(0, result.get(2).x);
        assertEquals(-1, result.get(2).y);
        assertEquals(1, result.get(3).x);
        assertEquals(-1, result.get(3).y);
        assertEquals(1, result.get(4).x);
        assertEquals(0, result.get(4).y);
    }

    @Test
    void testSteps10() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(10);
        assertEquals(6, result.size());
        assertEquals(-1, result.get(0).x);
        assertEquals(1, result.get(0).y);
        assertEquals(0, result.get(1).x);
        assertEquals(-1, result.get(1).y);
        assertEquals(0, result.get(2).x);
        assertEquals(0, result.get(2).y);
        assertEquals(0, result.get(3).x);
        assertEquals(1, result.get(3).y);
        assertEquals(1, result.get(4).x);
        assertEquals(-1, result.get(4).y);
        assertEquals(1, result.get(5).x);
        assertEquals(0, result.get(5).y);
    }

    @Test
    void testSteps10000() {
        List<SimulateLangtonsAnt.Coordinate> result = SimulateLangtonsAnt.simulateLangtonsAnt(10000);

        List<SimulateLangtonsAnt.Coordinate> expected = Arrays.asList(
            new SimulateLangtonsAnt.Coordinate(-19, 12),
            new SimulateLangtonsAnt.Coordinate(-19, 13),
            new SimulateLangtonsAnt.Coordinate(-18, 9),
            new SimulateLangtonsAnt.Coordinate(-18, 10),
            new SimulateLangtonsAnt.Coordinate(-18, 13),
            new SimulateLangtonsAnt.Coordinate(-18, 14),
            new SimulateLangtonsAnt.Coordinate(-17, 6),
            new SimulateLangtonsAnt.Coordinate(-17, 7),
            new SimulateLangtonsAnt.Coordinate(-17, 10),
            new SimulateLangtonsAnt.Coordinate(-17, 12),
            new SimulateLangtonsAnt.Coordinate(-17, 13),
            new SimulateLangtonsAnt.Coordinate(-17, 17),
            new SimulateLangtonsAnt.Coordinate(-16, -5),
            new SimulateLangtonsAnt.Coordinate(-16, -4),
            new SimulateLangtonsAnt.Coordinate(-16, -3),
            new SimulateLangtonsAnt.Coordinate(-16, -2),
            new SimulateLangtonsAnt.Coordinate(-16, 5),
            new SimulateLangtonsAnt.Coordinate(-16, 7),
            new SimulateLangtonsAnt.Coordinate(-16, 8),
            new SimulateLangtonsAnt.Coordinate(-16, 9),
            new SimulateLangtonsAnt.Coordinate(-16, 10),
            new SimulateLangtonsAnt.Coordinate(-16, 12),
            new SimulateLangtonsAnt.Coordinate(-16, 15),
            new SimulateLangtonsAnt.Coordinate(-16, 16),
            new SimulateLangtonsAnt.Coordinate(-16, 17),
            new SimulateLangtonsAnt.Coordinate(-15, -6),
            new SimulateLangtonsAnt.Coordinate(-15, -1),
            new SimulateLangtonsAnt.Coordinate(-15, 4),
            new SimulateLangtonsAnt.Coordinate(-15, 5),
            new SimulateLangtonsAnt.Coordinate(-15, 6),
            new SimulateLangtonsAnt.Coordinate(-15, 7),
            new SimulateLangtonsAnt.Coordinate(-15, 9),
            new SimulateLangtonsAnt.Coordinate(-15, 10),
            new SimulateLangtonsAnt.Coordinate(-15, 11),
            new SimulateLangtonsAnt.Coordinate(-15, 12),
            new SimulateLangtonsAnt.Coordinate(-15, 13),
            new SimulateLangtonsAnt.Coordinate(-15, 17),
            new SimulateLangtonsAnt.Coordinate(-14, -7),
            new SimulateLangtonsAnt.Coordinate(-14, -6),
            new SimulateLangtonsAnt.Coordinate(-14, -5),
            new SimulateLangtonsAnt.Coordinate(-14, 0),
            new SimulateLangtonsAnt.Coordinate(-14, 4),
            new SimulateLangtonsAnt.Coordinate(-14, 6),
            new SimulateLangtonsAnt.Coordinate(-14, 7),
            new SimulateLangtonsAnt.Coordinate(-14, 8),
            new SimulateLangtonsAnt.Coordinate(-14, 13),
            new SimulateLangtonsAnt.Coordinate(-14, 15),
            new SimulateLangtonsAnt.Coordinate(-14, 16),
            new SimulateLangtonsAnt.Coordinate(-14, 18),
            new SimulateLangtonsAnt.Coordinate(-13, -7),
            new SimulateLangtonsAnt.Coordinate(-13, -6),
            new SimulateLangtonsAnt.Coordinate(-13, -5),
            new SimulateLangtonsAnt.Coordinate(-13, 0),
            new SimulateLangtonsAnt.Coordinate(-13, 2),
            new SimulateLangtonsAnt.Coordinate(-13, 3),
            new SimulateLangtonsAnt.Coordinate(-13, 9),
            new SimulateLangtonsAnt.Coordinate(-13, 11),
            new SimulateLangtonsAnt.Coordinate(-13, 12),
            new SimulateLangtonsAnt.Coordinate(-13, 15),
            new SimulateLangtonsAnt.Coordinate(-13, 17),
            new SimulateLangtonsAnt.Coordinate(-13, 18),
            new SimulateLangtonsAnt.Coordinate(-12, -6),
            new SimulateLangtonsAnt.Coordinate(-12, -1),
            new SimulateLangtonsAnt.Coordinate(-12, 3),
            new SimulateLangtonsAnt.Coordinate(-12, 4),
            new SimulateLangtonsAnt.Coordinate(-12, 6),
            new SimulateLangtonsAnt.Coordinate(-12, 8),
            new SimulateLangtonsAnt.Coordinate(-12, 14),
            new SimulateLangtonsAnt.Coordinate(-12, 15),
            new SimulateLangtonsAnt.Coordinate(-11, -6),
            new SimulateLangtonsAnt.Coordinate(-11, -4),
            new SimulateLangtonsAnt.Coordinate(-11, 3),
            new SimulateLangtonsAnt.Coordinate(-11, 5),
            new SimulateLangtonsAnt.Coordinate(-11, 6),
            new SimulateLangtonsAnt.Coordinate(-11, 7),
            new SimulateLangtonsAnt.Coordinate(-11, 8),
            new SimulateLangtonsAnt.Coordinate(-11, 9),
            new SimulateLangtonsAnt.Coordinate(-11, 12),
            new SimulateLangtonsAnt.Coordinate(-11, 16),
            new SimulateLangtonsAnt.Coordinate(-10, -7),
            new SimulateLangtonsAnt.Coordinate(-10, -3),
            new SimulateLangtonsAnt.Coordinate(-10, -2),
            new SimulateLangtonsAnt.Coordinate(-10, -1),
            new SimulateLangtonsAnt.Coordinate(-10, 0),
            new SimulateLangtonsAnt.Coordinate(-10, 1),
            new SimulateLangtonsAnt.Coordinate(-10, 12),
            new SimulateLangtonsAnt.Coordinate(-10, 13),
            new SimulateLangtonsAnt.Coordinate(-10, 15),
            new SimulateLangtonsAnt.Coordinate(-10, 16),
            new SimulateLangtonsAnt.Coordinate(-10, 17),
            new SimulateLangtonsAnt.Coordinate(-10, 18),
            new SimulateLangtonsAnt.Coordinate(-10, 19),
            new SimulateLangtonsAnt.Coordinate(-10, 20),
            new SimulateLangtonsAnt.Coordinate(-9, -7),
            new SimulateLangtonsAnt.Coordinate(-9, -6),
            new SimulateLangtonsAnt.Coordinate(-9, -5),
            new SimulateLangtonsAnt.Coordinate(-9, -2),
            new SimulateLangtonsAnt.Coordinate(-9, -1),
            new SimulateLangtonsAnt.Coordinate(-9, 2),
            new SimulateLangtonsAnt.Coordinate(-9, 4),
            new SimulateLangtonsAnt.Coordinate(-9, 5),
            new SimulateLangtonsAnt.Coordinate(-9, 7),
            new SimulateLangtonsAnt.Coordinate(-9, 9),
            new SimulateLangtonsAnt.Coordinate(-9, 11),
            new SimulateLangtonsAnt.Coordinate(-9, 15),
            new SimulateLangtonsAnt.Coordinate(-9, 16),
            new SimulateLangtonsAnt.Coordinate(-9, 18),
            new SimulateLangtonsAnt.Coordinate(-9, 20),
            new SimulateLangtonsAnt.Coordinate(-9, 21),
            new SimulateLangtonsAnt.Coordinate(-8, -9),
            new SimulateLangtonsAnt.Coordinate(-8, -8),
            new SimulateLangtonsAnt.Coordinate(-8, -5),
            new SimulateLangtonsAnt.Coordinate(-8, -3),
            new SimulateLangtonsAnt.Coordinate(-8, -2),
            new SimulateLangtonsAnt.Coordinate(-8, -1),
            new SimulateLangtonsAnt.Coordinate(-8, 0),
            new SimulateLangtonsAnt.Coordinate(-8, 1),
            new SimulateLangtonsAnt.Coordinate(-8, 2),
            new SimulateLangtonsAnt.Coordinate(-8, 3),
            new SimulateLangtonsAnt.Coordinate(-8, 5),
            new SimulateLangtonsAnt.Coordinate(-8, 9),
            new SimulateLangtonsAnt.Coordinate(-8, 12),
            new SimulateLangtonsAnt.Coordinate(-8, 13),
            new SimulateLangtonsAnt.Coordinate(-8, 14),
            new SimulateLangtonsAnt.Coordinate(-8, 19),
            new SimulateLangtonsAnt.Coordinate(-8, 20),
            new SimulateLangtonsAnt.Coordinate(-8, 22),
            new SimulateLangtonsAnt.Coordinate(-7, -10),
            new SimulateLangtonsAnt.Coordinate(-7, -7),
            new SimulateLangtonsAnt.Coordinate(-7, -4),
            new SimulateLangtonsAnt.Coordinate(-7, -3),
            new SimulateLangtonsAnt.Coordinate(-7, -2),
            new SimulateLangtonsAnt.Coordinate(-7, -1),
            new SimulateLangtonsAnt.Coordinate(-7, 0),
            new SimulateLangtonsAnt.Coordinate(-7, 1),
            new SimulateLangtonsAnt.Coordinate(-7, 3),
            new SimulateLangtonsAnt.Coordinate(-7, 4),
            new SimulateLangtonsAnt.Coordinate(-7, 8),
            new SimulateLangtonsAnt.Coordinate(-7, 11),
            new SimulateLangtonsAnt.Coordinate(-7, 13),
            new SimulateLangtonsAnt.Coordinate(-7, 14),
            new SimulateLangtonsAnt.Coordinate(-7, 18),
            new SimulateLangtonsAnt.Coordinate(-7, 22),
            new SimulateLangtonsAnt.Coordinate(-6, -11),
            new SimulateLangtonsAnt.Coordinate(-6, -6),
            new SimulateLangtonsAnt.Coordinate(-6, -4),
            new SimulateLangtonsAnt.Coordinate(-6, -2),
            new SimulateLangtonsAnt.Coordinate(-6, -1),
            new SimulateLangtonsAnt.Coordinate(-6, 1),
            new SimulateLangtonsAnt.Coordinate(-6, 4),
            new SimulateLangtonsAnt.Coordinate(-6, 5),
            new SimulateLangtonsAnt.Coordinate(-6, 6),
            new SimulateLangtonsAnt.Coordinate(-6, 7),
            new SimulateLangtonsAnt.Coordinate(-6, 8),
            new SimulateLangtonsAnt.Coordinate(-6, 9),
            new SimulateLangtonsAnt.Coordinate(-6, 11),
            new SimulateLangtonsAnt.Coordinate(-6, 12),
            new SimulateLangtonsAnt.Coordinate(-6, 13),
            new SimulateLangtonsAnt.Coordinate(-6, 14),
            new SimulateLangtonsAnt.Coordinate(-6, 15),
            new SimulateLangtonsAnt.Coordinate(-6, 16),
            new SimulateLangtonsAnt.Coordinate(-6, 17),
            new SimulateLangtonsAnt.Coordinate(-6, 21),
            new SimulateLangtonsAnt.Coordinate(-5, -11),
            new SimulateLangtonsAnt.Coordinate(-5, -9),
            new SimulateLangtonsAnt.Coordinate(-5, -8),
            new SimulateLangtonsAnt.Coordinate(-5, -7),
            new SimulateLangtonsAnt.Coordinate(-5, -6),
            new SimulateLangtonsAnt.Coordinate(-5, -4),
            new SimulateLangtonsAnt.Coordinate(-5, -3),
            new SimulateLangtonsAnt.Coordinate(-5, -1),
            new SimulateLangtonsAnt.Coordinate(-5, 1),
            new SimulateLangtonsAnt.Coordinate(-5, 2),
            new SimulateLangtonsAnt.Coordinate(-5, 3),
            new SimulateLangtonsAnt.Coordinate(-5, 4),
            new SimulateLangtonsAnt.Coordinate(-5, 9),
            new SimulateLangtonsAnt.Coordinate(-5, 10),
            new SimulateLangtonsAnt.Coordinate(-5, 13),
            new SimulateLangtonsAnt.Coordinate(-5, 14),
            new SimulateLangtonsAnt.Coordinate(-5, 16),
            new SimulateLangtonsAnt.Coordinate(-5, 18),
            new SimulateLangtonsAnt.Coordinate(-5, 19),
            new SimulateLangtonsAnt.Coordinate(-5, 21),
            new SimulateLangtonsAnt.Coordinate(-4, -10),
            new SimulateLangtonsAnt.Coordinate(-4, -5),
            new SimulateLangtonsAnt.Coordinate(-4, -4),
            new SimulateLangtonsAnt.Coordinate(-4, -3),
            new SimulateLangtonsAnt.Coordinate(-4, -2),
            new SimulateLangtonsAnt.Coordinate(-4, 2),
            new SimulateLangtonsAnt.Coordinate(-4, 5),
            new SimulateLangtonsAnt.Coordinate(-4, 7),
            new SimulateLangtonsAnt.Coordinate(-4, 8),
            new SimulateLangtonsAnt.Coordinate(-4, 9),
            new SimulateLangtonsAnt.Coordinate(-4, 10),
            new SimulateLangtonsAnt.Coordinate(-4, 11),
            new SimulateLangtonsAnt.Coordinate(-4, 12),
            new SimulateLangtonsAnt.Coordinate(-4, 14),
            new SimulateLangtonsAnt.Coordinate(-4, 15),
            new SimulateLangtonsAnt.Coordinate(-4, 20),
            new SimulateLangtonsAnt.Coordinate(-4, 21),
            new SimulateLangtonsAnt.Coordinate(-4, 22),
            new SimulateLangtonsAnt.Coordinate(-3, -7),
            new SimulateLangtonsAnt.Coordinate(-3, -3),
            new SimulateLangtonsAnt.Coordinate(-3, -1),
            new SimulateLangtonsAnt.Coordinate(-3, 0),
            new SimulateLangtonsAnt.Coordinate(-3, 2),
            new SimulateLangtonsAnt.Coordinate(-3, 4),
            new SimulateLangtonsAnt.Coordinate(-3, 5),
            new SimulateLangtonsAnt.Coordinate(-3, 6),
            new SimulateLangtonsAnt.Coordinate(-3, 8),
            new SimulateLangtonsAnt.Coordinate(-3, 11),
            new SimulateLangtonsAnt.Coordinate(-3, 12),
            new SimulateLangtonsAnt.Coordinate(-3, 15),
            new SimulateLangtonsAnt.Coordinate(-3, 16),
            new SimulateLangtonsAnt.Coordinate(-3, 20),
            new SimulateLangtonsAnt.Coordinate(-3, 21),
            new SimulateLangtonsAnt.Coordinate(-3, 22),
            new SimulateLangtonsAnt.Coordinate(-2, -4),
            new SimulateLangtonsAnt.Coordinate(-2, -3),
            new SimulateLangtonsAnt.Coordinate(-2, -2),
            new SimulateLangtonsAnt.Coordinate(-2, -1),
            new SimulateLangtonsAnt.Coordinate(-2, 0),
            new SimulateLangtonsAnt.Coordinate(-2, 1),
            new SimulateLangtonsAnt.Coordinate(-2, 2),
            new SimulateLangtonsAnt.Coordinate(-2, 7),
            new SimulateLangtonsAnt.Coordinate(-2, 10),
            new SimulateLangtonsAnt.Coordinate(-2, 11),
            new SimulateLangtonsAnt.Coordinate(-2, 13),
            new SimulateLangtonsAnt.Coordinate(-2, 14),
            new SimulateLangtonsAnt.Coordinate(-2, 16),
            new SimulateLangtonsAnt.Coordinate(-2, 22),
            new SimulateLangtonsAnt.Coordinate(-1, -12),
            new SimulateLangtonsAnt.Coordinate(-1, -11),
            new SimulateLangtonsAnt.Coordinate(-1, -10),
            new SimulateLangtonsAnt.Coordinate(-1, -9),
            new SimulateLangtonsAnt.Coordinate(-1, -6),
            new SimulateLangtonsAnt.Coordinate(-1, -5),
            new SimulateLangtonsAnt.Coordinate(-1, -3),
            new SimulateLangtonsAnt.Coordinate(-1, -2),
            new SimulateLangtonsAnt.Coordinate(-1, 1),
            new SimulateLangtonsAnt.Coordinate(-1, 2),
            new SimulateLangtonsAnt.Coordinate(-1, 3),
            new SimulateLangtonsAnt.Coordinate(-1, 4),
            new SimulateLangtonsAnt.Coordinate(-1, 6),
            new SimulateLangtonsAnt.Coordinate(-1, 7),
            new SimulateLangtonsAnt.Coordinate(-1, 9),
            new SimulateLangtonsAnt.Coordinate(-1, 10),
            new SimulateLangtonsAnt.Coordinate(-1, 12),
            new SimulateLangtonsAnt.Coordinate(-1, 13),
            new SimulateLangtonsAnt.Coordinate(-1, 16),
            new SimulateLangtonsAnt.Coordinate(-1, 22),
            new SimulateLangtonsAnt.Coordinate(0, -13),
            new SimulateLangtonsAnt.Coordinate(0, -8),
            new SimulateLangtonsAnt.Coordinate(0, -6),
            new SimulateLangtonsAnt.Coordinate(0, -2),
            new SimulateLangtonsAnt.Coordinate(0, -1),
            new SimulateLangtonsAnt.Coordinate(0, 0),
            new SimulateLangtonsAnt.Coordinate(0, 2),
            new SimulateLangtonsAnt.Coordinate(0, 3),
            new SimulateLangtonsAnt.Coordinate(0, 5),
            new SimulateLangtonsAnt.Coordinate(0, 6),
            new SimulateLangtonsAnt.Coordinate(0, 7),
            new SimulateLangtonsAnt.Coordinate(0, 12),
            new SimulateLangtonsAnt.Coordinate(0, 14),
            new SimulateLangtonsAnt.Coordinate(0, 15),
            new SimulateLangtonsAnt.Coordinate(0, 16),
            new SimulateLangtonsAnt.Coordinate(0, 17),
            new SimulateLangtonsAnt.Coordinate(0, 22),
            new SimulateLangtonsAnt.Coordinate(1, -14),
            new SimulateLangtonsAnt.Coordinate(1, -13),
            new SimulateLangtonsAnt.Coordinate(1, -12),
            new SimulateLangtonsAnt.Coordinate(1, -4),
            new SimulateLangtonsAnt.Coordinate(1, -3),
            new SimulateLangtonsAnt.Coordinate(1, -2),
            new SimulateLangtonsAnt.Coordinate(1, 0),
            new SimulateLangtonsAnt.Coordinate(1, 2),
            new SimulateLangtonsAnt.Coordinate(1, 4),
            new SimulateLangtonsAnt.Coordinate(1, 5),
            new SimulateLangtonsAnt.Coordinate(1, 6),
            new SimulateLangtonsAnt.Coordinate(1, 7),
            new SimulateLangtonsAnt.Coordinate(1, 8),
            new SimulateLangtonsAnt.Coordinate(1, 13),
            new SimulateLangtonsAnt.Coordinate(1, 15),
            new SimulateLangtonsAnt.Coordinate(1, 22),
            new SimulateLangtonsAnt.Coordinate(2, -14),
            new SimulateLangtonsAnt.Coordinate(2, -12),
            new SimulateLangtonsAnt.Coordinate(2, -8),
            new SimulateLangtonsAnt.Coordinate(2, -7),
            new SimulateLangtonsAnt.Coordinate(2, -6),
            new SimulateLangtonsAnt.Coordinate(2, -4),
            new SimulateLangtonsAnt.Coordinate(2, -3),
            new SimulateLangtonsAnt.Coordinate(2, -2),
            new SimulateLangtonsAnt.Coordinate(2, -1),
            new SimulateLangtonsAnt.Coordinate(2, 1),
            new SimulateLangtonsAnt.Coordinate(2, 2),
            new SimulateLangtonsAnt.Coordinate(2, 4),
            new SimulateLangtonsAnt.Coordinate(2, 8),
            new SimulateLangtonsAnt.Coordinate(2, 9),
            new SimulateLangtonsAnt.Coordinate(2, 11),
            new SimulateLangtonsAnt.Coordinate(2, 12),
            new SimulateLangtonsAnt.Coordinate(2, 13),
            new SimulateLangtonsAnt.Coordinate(2, 15),
            new SimulateLangtonsAnt.Coordinate(2, 16),
            new SimulateLangtonsAnt.Coordinate(2, 22),
            new SimulateLangtonsAnt.Coordinate(3, -8),
            new SimulateLangtonsAnt.Coordinate(3, -7),
            new SimulateLangtonsAnt.Coordinate(3, -5),
            new SimulateLangtonsAnt.Coordinate(3, -4),
            new SimulateLangtonsAnt.Coordinate(3, -1),
            new SimulateLangtonsAnt.Coordinate(3, 0),
            new SimulateLangtonsAnt.Coordinate(3, 1),
            new SimulateLangtonsAnt.Coordinate(3, 2),
            new SimulateLangtonsAnt.Coordinate(3, 7),
            new SimulateLangtonsAnt.Coordinate(3, 8),
            new SimulateLangtonsAnt.Coordinate(3, 9),
            new SimulateLangtonsAnt.Coordinate(3, 10),
            new SimulateLangtonsAnt.Coordinate(3, 12),
            new SimulateLangtonsAnt.Coordinate(3, 14),
            new SimulateLangtonsAnt.Coordinate(3, 16),
            new SimulateLangtonsAnt.Coordinate(3, 22),
            new SimulateLangtonsAnt.Coordinate(4, -13),
            new SimulateLangtonsAnt.Coordinate(4, -8),
            new SimulateLangtonsAnt.Coordinate(4, -5),
            new SimulateLangtonsAnt.Coordinate(4, -4),
            new SimulateLangtonsAnt.Coordinate(4, 0),
            new SimulateLangtonsAnt.Coordinate(4, 1),
            new SimulateLangtonsAnt.Coordinate(4, 2),
            new SimulateLangtonsAnt.Coordinate(4, 5),
            new SimulateLangtonsAnt.Coordinate(4, 6),
            new SimulateLangtonsAnt.Coordinate(4, 7),
            new SimulateLangtonsAnt.Coordinate(4, 13),
            new SimulateLangtonsAnt.Coordinate(4, 14),
            new SimulateLangtonsAnt.Coordinate(4, 15),
            new SimulateLangtonsAnt.Coordinate(4, 22),
            new SimulateLangtonsAnt.Coordinate(5, -13),
            new SimulateLangtonsAnt.Coordinate(5, -12),
            new SimulateLangtonsAnt.Coordinate(5, -8),
            new SimulateLangtonsAnt.Coordinate(5, -7),
            new SimulateLangtonsAnt.Coordinate(5, -5),
            new SimulateLangtonsAnt.Coordinate(5, -4),
            new SimulateLangtonsAnt.Coordinate(5, -3),
            new SimulateLangtonsAnt.Coordinate(5, -1),
            new SimulateLangtonsAnt.Coordinate(5, 0),
            new SimulateLangtonsAnt.Coordinate(5, 1),
            new SimulateLangtonsAnt.Coordinate(5, 2),
            new SimulateLangtonsAnt.Coordinate(5, 5),
            new SimulateLangtonsAnt.Coordinate(5, 12),
            new SimulateLangtonsAnt.Coordinate(5, 13),
            new SimulateLangtonsAnt.Coordinate(5, 14),
            new SimulateLangtonsAnt.Coordinate(5, 18),
            new SimulateLangtonsAnt.Coordinate(5, 19),
            new SimulateLangtonsAnt.Coordinate(5, 22),
            new SimulateLangtonsAnt.Coordinate(6, -13),
            new SimulateLangtonsAnt.Coordinate(6, -12),
            new SimulateLangtonsAnt.Coordinate(6, -10),
            new SimulateLangtonsAnt.Coordinate(6, -8),
            new SimulateLangtonsAnt.Coordinate(6, -7),
            new SimulateLangtonsAnt.Coordinate(6, -6),
            new SimulateLangtonsAnt.Coordinate(6, -5),
            new SimulateLangtonsAnt.Coordinate(6, 1),
            new SimulateLangtonsAnt.Coordinate(6, 5),
            new SimulateLangtonsAnt.Coordinate(6, 8),
            new SimulateLangtonsAnt.Coordinate(6, 10),
            new SimulateLangtonsAnt.Coordinate(6, 11),
            new SimulateLangtonsAnt.Coordinate(6, 13),
            new SimulateLangtonsAnt.Coordinate(6, 14),
            new SimulateLangtonsAnt.Coordinate(6, 15),
            new SimulateLangtonsAnt.Coordinate(6, 17),
            new SimulateLangtonsAnt.Coordinate(6, 18),
            new SimulateLangtonsAnt.Coordinate(6, 22),
            new SimulateLangtonsAnt.Coordinate(7, -14),
            new SimulateLangtonsAnt.Coordinate(7, -13),
            new SimulateLangtonsAnt.Coordinate(7, -12),
            new SimulateLangtonsAnt.Coordinate(7, -11),
            new SimulateLangtonsAnt.Coordinate(7, -9),
            new SimulateLangtonsAnt.Coordinate(7, -8),
            new SimulateLangtonsAnt.Coordinate(7, -4),
            new SimulateLangtonsAnt.Coordinate(7, -3),
            new SimulateLangtonsAnt.Coordinate(7, -1),
            new SimulateLangtonsAnt.Coordinate(7, 0),
            new SimulateLangtonsAnt.Coordinate(7, 1),
            new SimulateLangtonsAnt.Coordinate(7, 2),
            new SimulateLangtonsAnt.Coordinate(7, 5),
            new SimulateLangtonsAnt.Coordinate(7, 7),
            new SimulateLangtonsAnt.Coordinate(7, 10),
            new SimulateLangtonsAnt.Coordinate(7, 13),
            new SimulateLangtonsAnt.Coordinate(7, 16),
            new SimulateLangtonsAnt.Coordinate(7, 17),
            new SimulateLangtonsAnt.Coordinate(7, 18),
            new SimulateLangtonsAnt.Coordinate(7, 22),
            new SimulateLangtonsAnt.Coordinate(8, -14),
            new SimulateLangtonsAnt.Coordinate(8, -12),
            new SimulateLangtonsAnt.Coordinate(8, -11),
            new SimulateLangtonsAnt.Coordinate(8, -9),
            new SimulateLangtonsAnt.Coordinate(8, -8),
            new SimulateLangtonsAnt.Coordinate(8, -7),
            new SimulateLangtonsAnt.Coordinate(8, -4),
            new SimulateLangtonsAnt.Coordinate(8, -2),
            new SimulateLangtonsAnt.Coordinate(8, 0),
            new SimulateLangtonsAnt.Coordinate(8, 1),
            new SimulateLangtonsAnt.Coordinate(8, 3),
            new SimulateLangtonsAnt.Coordinate(8, 5),
            new SimulateLangtonsAnt.Coordinate(8, 11),
            new SimulateLangtonsAnt.Coordinate(8, 13),
            new SimulateLangtonsAnt.Coordinate(8, 19),
            new SimulateLangtonsAnt.Coordinate(8, 21),
            new SimulateLangtonsAnt.Coordinate(9, -10),
            new SimulateLangtonsAnt.Coordinate(9, -8),
            new SimulateLangtonsAnt.Coordinate(9, -5),
            new SimulateLangtonsAnt.Coordinate(9, 0),
            new SimulateLangtonsAnt.Coordinate(9, 1),
            new SimulateLangtonsAnt.Coordinate(9, 3),
            new SimulateLangtonsAnt.Coordinate(9, 4),
            new SimulateLangtonsAnt.Coordinate(9, 7),
            new SimulateLangtonsAnt.Coordinate(9, 9),
            new SimulateLangtonsAnt.Coordinate(9, 12),
            new SimulateLangtonsAnt.Coordinate(9, 13),
            new SimulateLangtonsAnt.Coordinate(9, 14),
            new SimulateLangtonsAnt.Coordinate(9, 16),
            new SimulateLangtonsAnt.Coordinate(9, 17),
            new SimulateLangtonsAnt.Coordinate(10, -10),
            new SimulateLangtonsAnt.Coordinate(10, -9),
            new SimulateLangtonsAnt.Coordinate(10, -7),
            new SimulateLangtonsAnt.Coordinate(10, -2),
            new SimulateLangtonsAnt.Coordinate(10, 1),
            new SimulateLangtonsAnt.Coordinate(10, 2),
            new SimulateLangtonsAnt.Coordinate(10, 3),
            new SimulateLangtonsAnt.Coordinate(10, 4),
            new SimulateLangtonsAnt.Coordinate(10, 5),
            new SimulateLangtonsAnt.Coordinate(10, 7),
            new SimulateLangtonsAnt.Coordinate(10, 12),
            new SimulateLangtonsAnt.Coordinate(10, 17),
            new SimulateLangtonsAnt.Coordinate(10, 20),
            new SimulateLangtonsAnt.Coordinate(10, 22),
            new SimulateLangtonsAnt.Coordinate(11, -11),
            new SimulateLangtonsAnt.Coordinate(11, -9),
            new SimulateLangtonsAnt.Coordinate(11, -8),
            new SimulateLangtonsAnt.Coordinate(11, -6),
            new SimulateLangtonsAnt.Coordinate(11, -3),
            new SimulateLangtonsAnt.Coordinate(11, 2),
            new SimulateLangtonsAnt.Coordinate(11, 3),
            new SimulateLangtonsAnt.Coordinate(11, 5),
            new SimulateLangtonsAnt.Coordinate(11, 6),
            new SimulateLangtonsAnt.Coordinate(11, 8),
            new SimulateLangtonsAnt.Coordinate(11, 11),
            new SimulateLangtonsAnt.Coordinate(11, 12),
            new SimulateLangtonsAnt.Coordinate(11, 13),
            new SimulateLangtonsAnt.Coordinate(11, 20),
            new SimulateLangtonsAnt.Coordinate(11, 21),
            new SimulateLangtonsAnt.Coordinate(11, 22),
            new SimulateLangtonsAnt.Coordinate(12, -13),
            new SimulateLangtonsAnt.Coordinate(12, -11),
            new SimulateLangtonsAnt.Coordinate(12, -7),
            new SimulateLangtonsAnt.Coordinate(12, -4),
            new SimulateLangtonsAnt.Coordinate(12, -1),
            new SimulateLangtonsAnt.Coordinate(12, 2),
            new SimulateLangtonsAnt.Coordinate(12, 5),
            new SimulateLangtonsAnt.Coordinate(12, 6),
            new SimulateLangtonsAnt.Coordinate(12, 7),
            new SimulateLangtonsAnt.Coordinate(12, 11),
            new SimulateLangtonsAnt.Coordinate(12, 12),
            new SimulateLangtonsAnt.Coordinate(12, 15),
            new SimulateLangtonsAnt.Coordinate(12, 16),
            new SimulateLangtonsAnt.Coordinate(12, 21),
            new SimulateLangtonsAnt.Coordinate(13, -14),
            new SimulateLangtonsAnt.Coordinate(13, -13),
            new SimulateLangtonsAnt.Coordinate(13, -12),
            new SimulateLangtonsAnt.Coordinate(13, -10),
            new SimulateLangtonsAnt.Coordinate(13, -8),
            new SimulateLangtonsAnt.Coordinate(13, -7),
            new SimulateLangtonsAnt.Coordinate(13, -6),
            new SimulateLangtonsAnt.Coordinate(13, -5),
            new SimulateLangtonsAnt.Coordinate(13, -4),
            new SimulateLangtonsAnt.Coordinate(13, -2),
            new SimulateLangtonsAnt.Coordinate(13, -1),
            new SimulateLangtonsAnt.Coordinate(13, 0),
            new SimulateLangtonsAnt.Coordinate(13, 1),
            new SimulateLangtonsAnt.Coordinate(13, 2),
            new SimulateLangtonsAnt.Coordinate(13, 3),
            new SimulateLangtonsAnt.Coordinate(13, 5),
            new SimulateLangtonsAnt.Coordinate(13, 6),
            new SimulateLangtonsAnt.Coordinate(13, 7),
            new SimulateLangtonsAnt.Coordinate(13, 9),
            new SimulateLangtonsAnt.Coordinate(13, 10),
            new SimulateLangtonsAnt.Coordinate(13, 11),
            new SimulateLangtonsAnt.Coordinate(13, 12),
            new SimulateLangtonsAnt.Coordinate(13, 13),
            new SimulateLangtonsAnt.Coordinate(13, 14),
            new SimulateLangtonsAnt.Coordinate(13, 15),
            new SimulateLangtonsAnt.Coordinate(13, 17),
            new SimulateLangtonsAnt.Coordinate(13, 19),
            new SimulateLangtonsAnt.Coordinate(13, 20),
            new SimulateLangtonsAnt.Coordinate(14, -14),
            new SimulateLangtonsAnt.Coordinate(14, -12),
            new SimulateLangtonsAnt.Coordinate(14, -10),
            new SimulateLangtonsAnt.Coordinate(14, -5),
            new SimulateLangtonsAnt.Coordinate(14, -4),
            new SimulateLangtonsAnt.Coordinate(14, -3),
            new SimulateLangtonsAnt.Coordinate(14, -2),
            new SimulateLangtonsAnt.Coordinate(14, -1),
            new SimulateLangtonsAnt.Coordinate(14, 3),
            new SimulateLangtonsAnt.Coordinate(14, 4),
            new SimulateLangtonsAnt.Coordinate(14, 7),
            new SimulateLangtonsAnt.Coordinate(14, 8),
            new SimulateLangtonsAnt.Coordinate(14, 9),
            new SimulateLangtonsAnt.Coordinate(14, 10),
            new SimulateLangtonsAnt.Coordinate(14, 11),
            new SimulateLangtonsAnt.Coordinate(14, 13),
            new SimulateLangtonsAnt.Coordinate(14, 14),
            new SimulateLangtonsAnt.Coordinate(14, 15),
            new SimulateLangtonsAnt.Coordinate(14, 16),
            new SimulateLangtonsAnt.Coordinate(14, 17),
            new SimulateLangtonsAnt.Coordinate(15, -12),
            new SimulateLangtonsAnt.Coordinate(15, -9),
            new SimulateLangtonsAnt.Coordinate(15, -8),
            new SimulateLangtonsAnt.Coordinate(15, -4),
            new SimulateLangtonsAnt.Coordinate(15, 3),
            new SimulateLangtonsAnt.Coordinate(15, 6),
            new SimulateLangtonsAnt.Coordinate(15, 8),
            new SimulateLangtonsAnt.Coordinate(15, 9),
            new SimulateLangtonsAnt.Coordinate(15, 12),
            new SimulateLangtonsAnt.Coordinate(15, 13),
            new SimulateLangtonsAnt.Coordinate(15, 14),
            new SimulateLangtonsAnt.Coordinate(15, 16),
            new SimulateLangtonsAnt.Coordinate(15, 17),
            new SimulateLangtonsAnt.Coordinate(15, 18),
            new SimulateLangtonsAnt.Coordinate(16, -15),
            new SimulateLangtonsAnt.Coordinate(16, -14),
            new SimulateLangtonsAnt.Coordinate(16, -13),
            new SimulateLangtonsAnt.Coordinate(16, -12),
            new SimulateLangtonsAnt.Coordinate(16, -8),
            new SimulateLangtonsAnt.Coordinate(16, -7),
            new SimulateLangtonsAnt.Coordinate(16, -6),
            new SimulateLangtonsAnt.Coordinate(16, -5),
            new SimulateLangtonsAnt.Coordinate(16, -4),
            new SimulateLangtonsAnt.Coordinate(16, -2),
            new SimulateLangtonsAnt.Coordinate(16, -1),
            new SimulateLangtonsAnt.Coordinate(16, 0),
            new SimulateLangtonsAnt.Coordinate(16, 1),
            new SimulateLangtonsAnt.Coordinate(16, 2),
            new SimulateLangtonsAnt.Coordinate(16, 3),
            new SimulateLangtonsAnt.Coordinate(16, 4),
            new SimulateLangtonsAnt.Coordinate(16, 5),
            new SimulateLangtonsAnt.Coordinate(16, 6),
            new SimulateLangtonsAnt.Coordinate(16, 10),
            new SimulateLangtonsAnt.Coordinate(16, 12),
            new SimulateLangtonsAnt.Coordinate(17, -20),
            new SimulateLangtonsAnt.Coordinate(17, -19),
            new SimulateLangtonsAnt.Coordinate(17, -14),
            new SimulateLangtonsAnt.Coordinate(17, -11),
            new SimulateLangtonsAnt.Coordinate(17, -5),
            new SimulateLangtonsAnt.Coordinate(17, -4),
            new SimulateLangtonsAnt.Coordinate(17, -3),
            new SimulateLangtonsAnt.Coordinate(17, -1),
            new SimulateLangtonsAnt.Coordinate(17, 1),
            new SimulateLangtonsAnt.Coordinate(17, 5),
            new SimulateLangtonsAnt.Coordinate(17, 7),
            new SimulateLangtonsAnt.Coordinate(17, 8),
            new SimulateLangtonsAnt.Coordinate(17, 9),
            new SimulateLangtonsAnt.Coordinate(17, 12),
            new SimulateLangtonsAnt.Coordinate(17, 13),
            new SimulateLangtonsAnt.Coordinate(17, 14),
            new SimulateLangtonsAnt.Coordinate(18, -21),
            new SimulateLangtonsAnt.Coordinate(18, -18),
            new SimulateLangtonsAnt.Coordinate(18, -15),
            new SimulateLangtonsAnt.Coordinate(18, -14),
            new SimulateLangtonsAnt.Coordinate(18, -13),
            new SimulateLangtonsAnt.Coordinate(18, -12),
            new SimulateLangtonsAnt.Coordinate(18, -10),
            new SimulateLangtonsAnt.Coordinate(18, -9),
            new SimulateLangtonsAnt.Coordinate(18, -5),
            new SimulateLangtonsAnt.Coordinate(18, -4),
            new SimulateLangtonsAnt.Coordinate(18, -3),
            new SimulateLangtonsAnt.Coordinate(18, -1),
            new SimulateLangtonsAnt.Coordinate(18, 0),
            new SimulateLangtonsAnt.Coordinate(18, 4),
            new SimulateLangtonsAnt.Coordinate(18, 5),
            new SimulateLangtonsAnt.Coordinate(18, 6),
            new SimulateLangtonsAnt.Coordinate(18, 8),
            new SimulateLangtonsAnt.Coordinate(18, 9),
            new SimulateLangtonsAnt.Coordinate(18, 15),
            new SimulateLangtonsAnt.Coordinate(18, 16),
            new SimulateLangtonsAnt.Coordinate(19, -22),
            new SimulateLangtonsAnt.Coordinate(19, -21),
            new SimulateLangtonsAnt.Coordinate(19, -20),
            new SimulateLangtonsAnt.Coordinate(19, -15),
            new SimulateLangtonsAnt.Coordinate(19, -13),
            new SimulateLangtonsAnt.Coordinate(19, -12),
            new SimulateLangtonsAnt.Coordinate(19, -10),
            new SimulateLangtonsAnt.Coordinate(19, -8),
            new SimulateLangtonsAnt.Coordinate(19, -7),
            new SimulateLangtonsAnt.Coordinate(19, -6),
            new SimulateLangtonsAnt.Coordinate(19, -5),
            new SimulateLangtonsAnt.Coordinate(19, -4),
            new SimulateLangtonsAnt.Coordinate(19, 0),
            new SimulateLangtonsAnt.Coordinate(19, 5),
            new SimulateLangtonsAnt.Coordinate(19, 8),
            new SimulateLangtonsAnt.Coordinate(19, 11),
            new SimulateLangtonsAnt.Coordinate(19, 12),
            new SimulateLangtonsAnt.Coordinate(19, 14),
            new SimulateLangtonsAnt.Coordinate(19, 15),
            new SimulateLangtonsAnt.Coordinate(19, 16),
            new SimulateLangtonsAnt.Coordinate(20, -22),
            new SimulateLangtonsAnt.Coordinate(20, -20),
            new SimulateLangtonsAnt.Coordinate(20, -19),
            new SimulateLangtonsAnt.Coordinate(20, -18),
            new SimulateLangtonsAnt.Coordinate(20, -17),
            new SimulateLangtonsAnt.Coordinate(20, -16),
            new SimulateLangtonsAnt.Coordinate(20, -14),
            new SimulateLangtonsAnt.Coordinate(20, -12),
            new SimulateLangtonsAnt.Coordinate(20, -8),
            new SimulateLangtonsAnt.Coordinate(20, -7),
            new SimulateLangtonsAnt.Coordinate(20, -4),
            new SimulateLangtonsAnt.Coordinate(20, -3),
            new SimulateLangtonsAnt.Coordinate(20, 3),
            new SimulateLangtonsAnt.Coordinate(20, 8),
            new SimulateLangtonsAnt.Coordinate(20, 12),
            new SimulateLangtonsAnt.Coordinate(20, 15),
            new SimulateLangtonsAnt.Coordinate(21, -18),
            new SimulateLangtonsAnt.Coordinate(21, -17),
            new SimulateLangtonsAnt.Coordinate(21, -16),
            new SimulateLangtonsAnt.Coordinate(21, -15),
            new SimulateLangtonsAnt.Coordinate(21, -14),
            new SimulateLangtonsAnt.Coordinate(21, -13),
            new SimulateLangtonsAnt.Coordinate(21, -11),
            new SimulateLangtonsAnt.Coordinate(21, -10),
            new SimulateLangtonsAnt.Coordinate(21, -9),
            new SimulateLangtonsAnt.Coordinate(21, -8),
            new SimulateLangtonsAnt.Coordinate(21, -5),
            new SimulateLangtonsAnt.Coordinate(21, -4),
            new SimulateLangtonsAnt.Coordinate(21, -2),
            new SimulateLangtonsAnt.Coordinate(21, 2),
            new SimulateLangtonsAnt.Coordinate(21, 5),
            new SimulateLangtonsAnt.Coordinate(21, 6),
            new SimulateLangtonsAnt.Coordinate(21, 9),
            new SimulateLangtonsAnt.Coordinate(21, 11),
            new SimulateLangtonsAnt.Coordinate(21, 13),
            new SimulateLangtonsAnt.Coordinate(21, 14),
            new SimulateLangtonsAnt.Coordinate(22, -20),
            new SimulateLangtonsAnt.Coordinate(22, -19),
            new SimulateLangtonsAnt.Coordinate(22, -12),
            new SimulateLangtonsAnt.Coordinate(22, -10),
            new SimulateLangtonsAnt.Coordinate(22, -9),
            new SimulateLangtonsAnt.Coordinate(22, -8),
            new SimulateLangtonsAnt.Coordinate(22, -6),
            new SimulateLangtonsAnt.Coordinate(22, -5),
            new SimulateLangtonsAnt.Coordinate(22, -2),
            new SimulateLangtonsAnt.Coordinate(22, -1),
            new SimulateLangtonsAnt.Coordinate(22, 0),
            new SimulateLangtonsAnt.Coordinate(22, 1),
            new SimulateLangtonsAnt.Coordinate(22, 5),
            new SimulateLangtonsAnt.Coordinate(22, 9),
            new SimulateLangtonsAnt.Coordinate(22, 10),
            new SimulateLangtonsAnt.Coordinate(22, 11),
            new SimulateLangtonsAnt.Coordinate(23, -19),
            new SimulateLangtonsAnt.Coordinate(23, -16),
            new SimulateLangtonsAnt.Coordinate(23, -14),
            new SimulateLangtonsAnt.Coordinate(23, -13),
            new SimulateLangtonsAnt.Coordinate(23, -12),
            new SimulateLangtonsAnt.Coordinate(23, -11),
            new SimulateLangtonsAnt.Coordinate(23, -10),
            new SimulateLangtonsAnt.Coordinate(23, -7),
            new SimulateLangtonsAnt.Coordinate(23, -3),
            new SimulateLangtonsAnt.Coordinate(23, -1),
            new SimulateLangtonsAnt.Coordinate(23, 0),
            new SimulateLangtonsAnt.Coordinate(23, 4),
            new SimulateLangtonsAnt.Coordinate(23, 7),
            new SimulateLangtonsAnt.Coordinate(23, 10),
            new SimulateLangtonsAnt.Coordinate(24, -19),
            new SimulateLangtonsAnt.Coordinate(24, -18),
            new SimulateLangtonsAnt.Coordinate(24, -16),
            new SimulateLangtonsAnt.Coordinate(24, -15),
            new SimulateLangtonsAnt.Coordinate(24, -14),
            new SimulateLangtonsAnt.Coordinate(24, -12),
            new SimulateLangtonsAnt.Coordinate(24, -11),
            new SimulateLangtonsAnt.Coordinate(24, -10),
            new SimulateLangtonsAnt.Coordinate(24, -9),
            new SimulateLangtonsAnt.Coordinate(24, -8),
            new SimulateLangtonsAnt.Coordinate(24, -7),
            new SimulateLangtonsAnt.Coordinate(24, -6),
            new SimulateLangtonsAnt.Coordinate(24, 0),
            new SimulateLangtonsAnt.Coordinate(24, 6),
            new SimulateLangtonsAnt.Coordinate(24, 8),
            new SimulateLangtonsAnt.Coordinate(24, 9),
            new SimulateLangtonsAnt.Coordinate(25, -20),
            new SimulateLangtonsAnt.Coordinate(25, -18),
            new SimulateLangtonsAnt.Coordinate(25, -15),
            new SimulateLangtonsAnt.Coordinate(25, -14),
            new SimulateLangtonsAnt.Coordinate(25, -12),
            new SimulateLangtonsAnt.Coordinate(25, -11),
            new SimulateLangtonsAnt.Coordinate(25, -4),
            new SimulateLangtonsAnt.Coordinate(25, 0),
            new SimulateLangtonsAnt.Coordinate(25, 1),
            new SimulateLangtonsAnt.Coordinate(25, 6),
            new SimulateLangtonsAnt.Coordinate(26, -21),
            new SimulateLangtonsAnt.Coordinate(26, -18),
            new SimulateLangtonsAnt.Coordinate(26, -16),
            new SimulateLangtonsAnt.Coordinate(26, -15),
            new SimulateLangtonsAnt.Coordinate(26, -14),
            new SimulateLangtonsAnt.Coordinate(26, -13),
            new SimulateLangtonsAnt.Coordinate(26, -4),
            new SimulateLangtonsAnt.Coordinate(26, -3),
            new SimulateLangtonsAnt.Coordinate(26, -2),
            new SimulateLangtonsAnt.Coordinate(26, 1),
            new SimulateLangtonsAnt.Coordinate(26, 2),
            new SimulateLangtonsAnt.Coordinate(26, 5),
            new SimulateLangtonsAnt.Coordinate(27, -21),
            new SimulateLangtonsAnt.Coordinate(27, -19),
            new SimulateLangtonsAnt.Coordinate(27, -18),
            new SimulateLangtonsAnt.Coordinate(27, -16),
            new SimulateLangtonsAnt.Coordinate(27, -15),
            new SimulateLangtonsAnt.Coordinate(27, -14),
            new SimulateLangtonsAnt.Coordinate(27, -1),
            new SimulateLangtonsAnt.Coordinate(27, 0),
            new SimulateLangtonsAnt.Coordinate(27, 3),
            new SimulateLangtonsAnt.Coordinate(27, 4),
            new SimulateLangtonsAnt.Coordinate(28, -20),
            new SimulateLangtonsAnt.Coordinate(28, -19),
            new SimulateLangtonsAnt.Coordinate(29, -19),
            new SimulateLangtonsAnt.Coordinate(29, -18)
        );

        assertEquals(expected.size(), result.size());
        assertEquals(expected, result);
    }
}
